FROM python:3.8

#Environment dependencies
RUN apt-get update -yqq \
    && apt-get install -yqq --no-install-recommends \
        netcat \
    && apt-get -q clean     

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app


COPY ./requirements.txt /usr/src/app/requirements.txt

RUN pip install -r requirements.txt

COPY . /usr/src/app

CMD ["./entrypoint.sh"]